---
driver:
  name: vagrant
  customize:
    memory: 8048
    cpus: 4

provisioner:
  name: chef_solo

platforms:
  - name: 'mwrock/Windows2012R2'
    transport:
      name: winrm
suites:
  - name: default
    run_list:
      - recipe[Incredibuild-Cookbook::default]
    attributes:
      incredibuild:
        url: "http://IBSetupConsole.exe"
        install:
          coordinator: "incredibuild/"
